displayName=ToA Invocation Display
author=noahnoah711
description=Shows the active Tombs of Amascut invocations for the room you are currently in.
tags=toa,tombs of amascut,invocations,raids,invocation display
plugins=com.github.noahnoah711.toainvocationdisplay.ToaInvocationDisplayPlugin
